version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shapedb
      MYSQL_USER: shapeuser
      MYSQL_PASSWORD: shapepassword
    ports:
        - "3307:3306"
    volumes:
        - ./mysql_data:/var/lib/mysql

