### POST request to create a new Shape
POST http://localhost:8000/api/shapes
Content-Type: application/json


{
  "name": "Triangle-B2",
  "type": "TRIANGLE",
  "vertices": [
    { "x": 35, "y": 35 },
    { "x": 45, "y": 55 },
    { "x": 25, "y": 15 }
  ]
}
