### POST request to create a new Shape
POST http://localhost:8000/api/shapes
Content-Type: application/json


{
  "name": "Circle-A4",
  "type": "CIRCLE",
  "centerX": 900,
  "centerY": 900,
  "radius": 25
}