### POST request to create a new Shape with Basic Auth
POST http://localhost:8000/api/shapes
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "name": "Triangle-B9",
  "type": "TRIANGLE",
  "vertices": [
    { "x": 35, "y": 35 },
    { "x": 45, "y": 55 },
    { "x": 25, "y": 15 }
  ]
}
